version: 2

updates:
  # Monorepo npm dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      time: '02:00'
      day: saturday
      timezone: Etc/UTC
    labels:
      - automerge
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
    open-pull-requests-limit: 2
    groups:
      minor-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Infra npm dependencies
  - package-ecosystem: npm
    directory: /infra
    schedule:
      interval: weekly
      time: '03:00'
      timezone: Etc/UTC
    labels:
      - automerge
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-infra)
    open-pull-requests-limit: 2
    groups:
      minor-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: '04:00'
      timezone: Etc/UTC
    labels:
      - automerge
      - dependencies
    commit-message:
      prefix: chore(ci)
    open-pull-requests-limit: 2
    groups:
      minor-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # GitHub Actions npm dependencies
  - package-ecosystem: npm
    directory: /.github/actions/
    schedule:
      interval: weekly
      day: saturday
      time: '05:00'
      timezone: Etc/UTC
    labels:
      - automerge
      - dependencies
    commit-message:
      prefix: chore(ci-deps)
    open-pull-requests-limit: 2
    groups:
      minor-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # CI Scripts dependencies
  - package-ecosystem: npm
    directory: /scripts/ci/cache
    schedule:
      interval: weekly
      day: saturday
      time: '06:00'
      timezone: Etc/UTC
    labels:
      - automerge
      - dependencies
    commit-message:
      prefix: chore(ci-deps)
    open-pull-requests-limit: 2
    groups:
      minor-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
